CXX = g++
CXX_Flags = -g -Wall

Practica 5: aritmetic_operator

aritmetic_operators: aritmetic_operators.cc
	$(CXX) $(CXX_Flags) -o aritmetic_operators.out aritmetic_operators.cc

.PHONY: clean
clean: 
	rm -f *.out