CXX = g++
CXX_Flags = -g -Wall

Practica08: harmonic-number2.cc

harmonic-number2: harmonic-number2.cc
	$(CXX) $(CXX_Flags) -o harmonic-number2.out harmonic-number2.cc

.PHONY: clean
clean: 
	rm -f *.out $(TARGET)