CXX = g++
CXX_Flags = -g -Wall

Practica08: first-position.cc

first-position: first-position.cc
	$(CXX) $(CXX_Flags) -o first-position.out first-position.cc

.PHONY: clean
clean: 
	rm -f *.out $(TARGET)