CXX = g++
CXX_Flags = -g -Wall

Practica 06: longest_shortest

longest_shortest: longest_shortest.cc
	$(CXX) $(CXX_Flags) -o longest_shortest.out longest_shortest.cc

.PHONY: clean
clean: 
	rm -f *.out