CXX = g++
CXX_Flags = -g -Wall

Practica08: harmonic-number.cc

harmonic-number: harmonic-number.cc
	$(CXX) $(CXX_Flags) -o harmonic-number.out harmonic-number.cc

.PHONY: clean
clean: 
	rm -f *.out $(TARGET)