CXX = g++
CXX_Flags = -g -Wall

Practica 5: booleans_operators

aritmetic_operators: booleans_operators.cc
	$(CXX) $(CXX_Flags) -o booleans_operators.out booleans_operators.cc

.PHONY: clean
clean: 
	rm -f *.out