CXX = g++
CXX_Flags = -g -Wall

Practica 6: time_descomposition

dividers: time_descomposition.cc
	$(CXX) $(CXX_Flags) -o time_descomposition.out time_descomposition.cc

.PHONY: clean
clean: 
	rm -f *.out